spring:
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://localhost:5432/schedule_db
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver
    secondary:
      jdbc-url: jdbc:postgresql://localhost:5432/users_db
      username: notpostgres
      password: 5678
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
   jpa:
    repositories:
     enabled: true

logging:
  level:
    sql: debug
    web: debug
