spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
